spring:
  data:
    redis:
      host: localhost
      port: 6379
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  config:
     import: jwt-public-urls.yml
jwt:
  secret: "bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfdGlja2V0X3N5c3RlbQ=="  # 這是一個 Base64 編碼的字串
  expiration: 86400000
